#######################################
#	RememberHighestOnline插件   
# 记录最高同时在线玩家并发送公告 
#	      作者:CMD丶BLOCK_       
#		   QQ:1056293351           
######################################
#记录最高同时在线玩家(改了有何意义233)
Highest: 0
#是否公告
sendMessageToAllPlayer: true
#公告信息(%max%为当前在线人数)
Message: "§b服务器最高在线人数突破 %max% 人了！"